// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Nicknamezz00/go-microservice/internal/app/products"
	"github.com/Nicknamezz00/go-microservice/internal/app/products/controllers"
	grpc2 "github.com/Nicknamezz00/go-microservice/internal/app/products/grpc"
	"github.com/Nicknamezz00/go-microservice/internal/app/products/services"
	"github.com/Nicknamezz00/go-microservice/internal/pkg/app"
	"github.com/Nicknamezz00/go-microservice/internal/pkg/config"
	"github.com/Nicknamezz00/go-microservice/internal/pkg/consul"
	"github.com/Nicknamezz00/go-microservice/internal/pkg/jaeger"
	"github.com/Nicknamezz00/go-microservice/internal/pkg/log"
	"github.com/Nicknamezz00/go-microservice/internal/pkg/transports/grpc"
	"github.com/Nicknamezz00/go-microservice/internal/pkg/transports/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApp(f string) (*app.Application, error) {
	viper, err := config.NewViper(f)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	productsOptions, err := products.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	httpOptions, err := http.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	consulOptions, err := consul.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	configuration, err := jaeger.NewConfiguration(viper, logger)
	if err != nil {
		return nil, err
	}
	tracer, err := jaeger.NewJaeger(configuration)
	if err != nil {
		return nil, err
	}
	clientOptions, err := grpc.NewClientOptions(viper, tracer)
	if err != nil {
		return nil, err
	}
	client, err := grpc.NewClient(consulOptions, clientOptions)
	if err != nil {
		return nil, err
	}
	detailsClient, err := grpc2.NewDetailsClient(client)
	if err != nil {
		return nil, err
	}
	ratingsClient, err := grpc2.NewRatingsClient(client)
	if err != nil {
		return nil, err
	}
	reviewsClient, err := grpc2.NewReviewsClient(client)
	if err != nil {
		return nil, err
	}
	productsService := services.NewProductService(logger, detailsClient, ratingsClient, reviewsClient)
	productsController := controllers.NewProductsController(logger, productsService)
	initControllers := controllers.CreateInitControllers(productsController)
	engine := http.NewRouter(httpOptions, logger, initControllers, tracer)
	apiClient, err := consul.NewConsulClient(consulOptions)
	if err != nil {
		return nil, err
	}
	server, err := http.NewServer(httpOptions, logger, engine, apiClient)
	if err != nil {
		return nil, err
	}
	application, err := products.NewApp(productsOptions, logger, server)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

var providerSet = wire.NewSet(log.ProviderSet, config.ProviderSet, consul.ProviderSet, jaeger.ProviderSet, http.ProviderSet, grpc.ProviderSet, controllers.ProviderSet, grpc2.ProviderSet, services.ProviderSet, products.ProviderSet)
