version: '3'
services:
  details:
    user: "root"
    build:
      context: ..
      dockerfile: "build/package/details/Dockerfile"
    command: ./wait-for db:3306 -t 30 -- ./app
    depends_on:
      - db
    ports:
      - "8081:8081"

  products:
    user: "root"
    build:
      context: ..
      dockerfile: "build/package/products/Dockerfile"
    command: ./wait-for db:3306 -t 30 -- ./app
    depends_on:
      - db
    ports:
      - "8080:8080"

  ratings:
    user: "root"
    build:
      context: ..
      dockerfile: "build/package/ratings/Dockerfile"
    command: ./wait-for db:3306 -t 30 -- ./app
    depends_on:
      - db

  reviews:
    user: "root"
    build:
      context: ..
      dockerfile: "build/package/reviews/Dockerfile"
    command: ./wait-for db:3306 -t 30 -- ./app
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: products
      MYSQL_USER: products
      MYSQL_PASSWORD: 123456
    volumes:
      - ../scripts/products.sql:/docker-entrypoint-initdb.d/products.sql

