// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ratings.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRatingsRequest struct {
	ProductID            uint64   `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingsRequest) Reset()         { *m = GetRatingsRequest{} }
func (m *GetRatingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRatingsRequest) ProtoMessage()    {}
func (*GetRatingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf07e2fe2aafa921, []int{0}
}

func (m *GetRatingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingsRequest.Unmarshal(m, b)
}
func (m *GetRatingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingsRequest.Marshal(b, m, deterministic)
}
func (m *GetRatingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingsRequest.Merge(m, src)
}
func (m *GetRatingsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRatingsRequest.Size(m)
}
func (m *GetRatingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingsRequest proto.InternalMessageInfo

func (m *GetRatingsRequest) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

type Rating struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductID            uint64               `protobuf:"varint,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Score                uint64               `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	UpdatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf07e2fe2aafa921, []int{1}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rating) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *Rating) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Rating) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRatingsRequest)(nil), "GetRatingsRequest")
	proto.RegisterType((*Rating)(nil), "Rating")
}

func init() { proto.RegisterFile("ratings.proto", fileDescriptor_bf07e2fe2aafa921) }

var fileDescriptor_bf07e2fe2aafa921 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2c, 0xc9,
	0xcc, 0x4b, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf,
	0x49, 0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73,
	0x0b, 0x20, 0x0a, 0x94, 0x0c, 0xb9, 0x04, 0xdd, 0x53, 0x4b, 0x82, 0x20, 0x9a, 0x82, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0x0b, 0x8a, 0xf2, 0x53, 0x4a, 0x93, 0x4b, 0x3c,
	0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0x10, 0x02, 0x4a, 0x5d, 0x8c, 0x5c, 0x6c, 0x10,
	0x0d, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x50, 0x15, 0x4c, 0x99, 0x29, 0xa8, 0x1a, 0x99, 0xd0,
	0x34, 0x0a, 0x89, 0x70, 0xb1, 0x16, 0x27, 0xe7, 0x17, 0xa5, 0x4a, 0x30, 0x83, 0x65, 0x20, 0x1c,
	0x21, 0x1b, 0x2e, 0xee, 0xd2, 0x82, 0x94, 0xc4, 0x92, 0xd4, 0x94, 0x90, 0xcc, 0xdc, 0x54, 0x09,
	0x16, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x29, 0x3d, 0x88, 0xc3, 0xf5, 0x60, 0x0e, 0xd7, 0x0b, 0x81,
	0x39, 0x3c, 0x08, 0x59, 0xb9, 0x91, 0x2e, 0x17, 0x3b, 0xd4, 0xf1, 0x42, 0x4a, 0x5c, 0xcc, 0xee,
	0xa9, 0x25, 0x42, 0x42, 0x7a, 0x18, 0x1e, 0x92, 0x62, 0xd7, 0x83, 0x08, 0x38, 0xb1, 0x47, 0xb1,
	0x42, 0x4c, 0x64, 0x03, 0x53, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xf3, 0x68, 0x67,
	0x30, 0x01, 0x00, 0x00,
}
